outputs : src/regfile.sv config.yaml
	/usr/local/bin/librelane config.yaml --run-tag work --save-views-to outputs --manual-pdk --pdk-root $(PDK_ROOT)
.PHONY: outputs

check_librelane: 
	which librelane
