module chip_io #(
    parameter numGPIO = 16
) (
    // Power and ground connections
    inout vccd,
    inout vssd,
    inout vddio,
    inout vssio,
    
    // Ring resets
    input porb_h, // power-on reset, sense inverted, 3.3V domain
    input por,    // power on reset, noninverted, 1.8V domain
    
    // GPIO 
    inout [numGPIO-1:0] gpio_pad, // physical pad is inout
    output [numGPIO-1:0] gpio_in,
    input [numGPIO-1:0] gpio_out,

    // Pad config from core
    // Note there's a bunch of other config, but we tied those.
    input [numGPIO-1:0] dm2,
    input [numGPIO-1:0] dm1,
    input [numGPIO-1:0] dm0,
    input [numGPIO-1:0] oe_n,
    input [numGPIO-1:0] hld_ovr,
    input [numGPIO-1:0] ib_mode_sel
);

    // Quiet supplies
    wire vddio_q; 
    wire vssio_q;

    // Analog test bus rings
    wire analog_a_ring;
    wire analog_b_ring;
    
    // Per-pad tie low signal
    wire [numGPIO-1:0] tielow;

    // GPIO input pads
    genvar i;
    generate
        for (i = 0; i < numGPIO; i = i + 1) begin : gpio_pads
            sky130_ef_io__gpiov2_pad_wrapped u_gpio_pad (
                .AMUXBUS_A       (analog_a_ring), // analog test signal a
                .AMUXBUS_B       (analog_b_ring), // analog test signal b
                .ANALOG_EN       (vssd), // all analog test features disabled
                .ANALOG_POL      (vssd), // all analog test features disabled
                .ANALOG_SEL      (vssd), // all analog test features disabled
                .DM              ({ dm2[i], dm1[i], dm0[i] }), // From core
                .ENABLE_H        (porb_h), // tied to 3.3V nrst = 1 in normal operation
                .ENABLE_INP_H    (tielow[i]), // tied to VSS to always enable input
                .ENABLE_VDDA_H   (porb_h), // tied to 3.3V nrst = 1 in normal operation
                .ENABLE_VDDIO    (vccd),
                .ENABLE_VSWITCH_H(vssio), // tied to VSS to always enable input
                .HLD_H_N         (vddio), // hold pad state active low
                .HLD_OVR         (hld_ovr[i]), // From core
                .IB_MODE_SEL     (ib_mode_sel[i]), // From core
                .IN              (gpio_in[i]), // From core
                .INP_DIS         (por), // tied to 3.3V nrst = 1 in normal operation
                .IN_H            (), // From core
                .OE_N            (oe_n[i]), // From core
                .OUT             (gpio_out[i]), // From core
                .PAD             (gpio_pad[i]),
                .PAD_A_ESD_0_H   (), // these connect straight to the padzf
                .PAD_A_ESD_1_H   (), // these connect straight to the pad
                .PAD_A_NOESD_H   (), // these connect straight to the pad
                .SLOW            (vssd), // From core
                .TIE_HI_ESD      (),
                .TIE_LO_ESD      (tielow[i]),
                .VCCD            (vccd), // 1.8V core supply
                .VCCHIB          (vccd), // hibernate supply, can just be vccd too
                .VDDA            (vddio), // used for analog testing, tie to 3.3V if unused
                .VDDIO           (vddio), // 3.3V I/O supply
                .VDDIO_Q         (vddio_q), // Quiet 3.3 supply
                .VSSA            (vssio), // used for analog testing, tie to vssio if unused
                .VSSD            (vssd),
                .VSSIO           (vssio),
                .VSSIO_Q         (vssio_q),
                .VSWITCH         (vddio),
                .VTRIP_SEL       (vssd) // From core
          );
        end
    endgenerate

    // RST pad - sky130_fd_io__top_xres type pads
    // Just a GPIO pad with an RC filter
    // TODO: We'll put this in later

    // POWER PADS
    // We forgo VSSA/VCCA pads.
    // VDDIO_Q is used for lower current circuits in the pads, and is generated by default
    // Still for review if things like the hibernate voltage or analog voltage aren't actually optional and can't be shorted to VDDC/VDDIO.

    // VDDC pad
    sky130_ef_io__vccd_lvc_pad u_vccd_pad (
      .AMUXBUS_A   (analog_a_ring),
      .AMUXBUS_B   (analog_b_ring),
      .BDY2_B2B    (vssio),
      .DRN_LVC1    (vccd),
      .DRN_LVC2    (vccd),
      .SRC_BDY_LVC1(vssd),
      .SRC_BDY_LVC2(vssd),
      .VCCD        (vccd),
      .VCCHIB      (vccd),
      .VDDA        (vddio),
      .VDDIO       (vddio),
      .VDDIO_Q     (vddio_q),
      .VSSA        (vssio),
      .VSSD        (vssd),
      .VSSIO       (vssio),
      .VSSIO_Q     (vssio_q),
      .VSWITCH     (vddio)
    );
    // VSSC pad
    sky130_ef_io__vssd_lvc_pad u_vssd_pad (
      .AMUXBUS_A   (analog_a_ring),
      .AMUXBUS_B   (analog_b_ring),
      .BDY2_B2B    (vssio),
      .DRN_LVC1    (vssd),
      .DRN_LVC2    (vssd),
      .SRC_BDY_LVC1(vssd),
      .SRC_BDY_LVC2(vssd),
      .VCCD        (vccd),
      .VCCHIB      (vccd),
      .VDDA        (vddio),
      .VDDIO       (vddio),
      .VDDIO_Q     (vddio_q),
      .VSSA        (vssio),
      .VSSD        (vssd),
      .VSSIO       (vssio),
      .VSSIO_Q     (vssio_q),
      .VSWITCH     (vddio)
    );

    // VDDIO pad
    sky130_ef_io__vddio_hvc_pad u_vddio_pad  (
        .AMUXBUS_A  (analog_a_ring),
        .AMUXBUS_B  (analog_b_ring),
        .DRN_HVC    (vddio),
        .SRC_BDY_HVC(vssio),
        .VCCD       (vccd),
        .VCCHIB     (vccd),
        .VDDA       (vddio),
        .VDDIO      (vddio),
        .VDDIO_Q    (vddio_q),
        .VSSA       (vssio),
        .VSSD       (vssd),
        .VSSIO      (vssio),
        .VSSIO_Q    (vssio_q),
        .VSWITCH    (vddio)
    );

    // VSSIO pad
    sky130_ef_io__vssio_hvc_pad u_vssio_pad  (
        .AMUXBUS_A  (analog_a_ring),
        .AMUXBUS_B  (analog_b_ring),
        .DRN_HVC    (vddio),
        .SRC_BDY_HVC(vssio),
        .VCCD       (vccd),
        .VCCHIB     (vccd),
        .VDDA       (vddio),
        .VDDIO      (vddio),
        .VDDIO_Q    (vddio_q),
        .VSSA       (vssio),
        .VSSD       (vssd),
        .VSSIO      (vssio),
        .VSSIO_Q    (vssio_q),
        .VSWITCH    (vddio)
    );

endmodule