// Auto-generated by LibreLane
module regfile(
`ifdef USE_POWER_PINS
  inout vccd,
  inout vssd,
`endif
  input clk,
  input nrst,
  input we,
  input[3:0] addr,
  input[3:0] wdata,
  output[3:0] rdata
);
endmodule
