// Auto-generated by LibreLane
module regfile(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input nrst,
  input we,
  input[4:0] addr,
  input[7:0] wdata,
  output[7:0] rdata
);
endmodule
